#ifndef DOSJUN_BARD_H
#define DOSJUN_BARD_H

/* I N C L U D E S /////////////////////////////////////////////////////// */

#include "combat.h"

/* D E F I N E S ///////////////////////////////////////////////////////// */

#define JOB_LEVELS	10

/* P R O T O T Y P E S /////////////////////////////////////////////////// */

bool Check_Sing(targ source);
void Sing(targ source, targ target);

#endif
