#ifndef DOSJUN_FIGHTER_H
#define DOSJUN_FIGHTER_H

/* I N C L U D E S /////////////////////////////////////////////////////// */

#include "combat.h"

/* D E F I N E S ///////////////////////////////////////////////////////// */

/* P R O T O T Y P E S /////////////////////////////////////////////////// */

bool Check_Concentrate(combatant *source);
void Concentrate(combatant *source, combatant *target);

#endif
