CFLAGS = -G -I\TC\INCLUDE -I..\LIB -L\TC\LIB -mc
DEMO_OBJS = mkdemo.obj campaign.obj io.obj items.obj monsters.obj save.obj zone.obj
MAIN_OBJS = dosjun.obj campaign.obj fp.obj gfx.obj input.obj io.obj items.obj main.obj mem.obj monsters.obj party.obj save.obj zone.obj
EDITOR_OBJS = editor.obj gfx.obj input.obj io.obj jc.obj jc_lex.obj jc_par.obj mem.obj save.obj zone.obj
JCC_OBJS = jcc.obj jc.obj jc_lex.obj jc_par.obj mem.obj
HEADERS = code.h common.h dosjun.h files.h jc.h

all: dosjun editor jcc

dosjun: $(MAIN_OBJS)
	TCC $(CFLAGS) DOSJUN.OBJ DOSJUN.LIB ..\LIB\GAMELIB.LIB

editor: $(EDITOR_OBJS)
	TCC $(CFLAGS) EDITOR.OBJ DOSJUN.LIB ..\LIB\GAMELIB.LIB

demo: $(DEMO_OBJS)
	TCC $(CFLAGS) MKDEMO.OBJ DOSJUN.LIB
	MKDEMO

jcc: $(JCC_OBJS)
	TCC $(CFLAGS) $(JCC_OBJS)

campaign.obj: campaign.c $(HEADERS)
	TCC $(CFLAGS) -c campaign.c
	TLIB DOSJUN.LIB +-campaign.obj, DOSJUN.TXT

code.obj: code.c $(HEADERS)
	TCC $(CFLAGS) -c code.c
	TLIB DOSJUN.LIB +-code.obj, DOSJUN.TXT

dosjun.obj: dosjun.c $(HEADERS)
	TCC $(CFLAGS) -c dosjun.c

editor.obj: editor.c $(HEADERS)
	TCC $(CFLAGS) -c editor.c

fp.obj: fp.c $(HEADERS)
	TCC $(CFLAGS) -c fp.c
	TLIB DOSJUN.LIB +-fp.obj, DOSJUN.TXT

gfx.obj: gfx.c $(HEADERS)
	TCC $(CFLAGS) -c gfx.c
	TLIB DOSJUN.LIB +-gfx.obj, DOSJUN.TXT

input.obj: input.c $(HEADERS)
	TCC $(CFLAGS) -c input.c
	TLIB DOSJUN.LIB +-input.obj, DOSJUN.TXT

io.obj: io.c $(HEADERS)
	TCC $(CFLAGS) -c io.c
	TLIB DOSJUN.LIB +-io.obj, DOSJUN.TXT

items.obj: items.c $(HEADERS)
	TCC $(CFLAGS) -c items.c
	TLIB DOSJUN.LIB +-items.obj, DOSJUN.TXT

jc.obj: jc.c $(HEADERS)
	TCC $(CFLAGS) -c jc.c
	TLIB DOSJUN.LIB +-jc.obj, DOSJUN.TXT

jc_lex.obj: jc_lex.c $(HEADERS)
	TCC $(CFLAGS) -c jc_lex.c
	TLIB DOSJUN.LIB +-jc_lex.obj, DOSJUN.TXT

jc_par.obj: jc_par.c $(HEADERS)
	TCC $(CFLAGS) -c jc_par.c
	TLIB DOSJUN.LIB +-jc_par.obj, DOSJUN.TXT

jcc.obj: jcc.c $(HEADERS)
	TCC $(CFLAGS) -c jcc.c

main.obj: main.c $(HEADERS)
	TCC $(CFLAGS) -c main.c
	TLIB DOSJUN.LIB +-main.obj, DOSJUN.TXT

mem.obj: mem.c $(HEADERS)
	TCC $(CFLAGS) -c mem.c
	TLIB DOSJUN.LIB +-mem.obj, DOSJUN.TXT

mkdemo.obj: mkdemo.c $(HEADERS)
	TCC $(CFLAGS) -c mkdemo.c

monsters.obj: monsters.c $(HEADERS)
	TCC $(CFLAGS) -c monsters.c
	TLIB DOSJUN.LIB +-monsters.obj, DOSJUN.TXT

party.obj: party.c $(HEADERS)
	TCC $(CFLAGS) -c party.c
	TLIB DOSJUN.LIB +-PARTY.OBJ, DOSJUN.TXT

save.obj: save.c $(HEADERS)
	TCC $(CFLAGS) -c save.c
	TLIB DOSJUN.LIB +-save.obj, DOSJUN.TXT

zone.obj: zone.c $(HEADERS)
	TCC $(CFLAGS) -c zone.c
	TLIB DOSJUN.LIB +-zone.obj, DOSJUN.TXT

clean:
	-DEL *.OBJ
	-DEL *.EXE
